// Fallback mock data for when backend is unreachable

export const MOCK_SONGS = [
  {
    id: 'mock-1',
    title: 'Midnight Dreams',
    artist: 'Luna Wave',
    album: 'Neon Nights',
    cover_url: 'https://picsum.photos/seed/song1/300/300',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    duration: 234,
    genre: 'Electronic',
    play_count: 12450,
    download_count: 890,
    file_size: 4500000,
    cover_size: 150000,
    is_visible: true,
    show_in_new_releases: true,
    show_in_trending: true,
    is_premium_only: false,
  },
  {
    id: 'mock-2',
    title: 'Sunset Boulevard',
    artist: 'The Groove',
    album: 'Golden Hour',
    cover_url: 'https://picsum.photos/seed/song2/300/300',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    duration: 198,
    genre: 'Pop',
    play_count: 8920,
    download_count: 560,
    file_size: 3800000,
    cover_size: 120000,
    is_visible: true,
    show_in_new_releases: true,
    show_in_trending: false,
    is_premium_only: false,
  },
  {
    id: 'mock-3',
    title: 'Electric Pulse',
    artist: 'Neon Circuit',
    album: 'Voltage',
    cover_url: 'https://picsum.photos/seed/song3/300/300',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    duration: 267,
    genre: 'EDM',
    play_count: 15600,
    download_count: 1200,
    file_size: 5200000,
    cover_size: 180000,
    is_visible: true,
    show_in_new_releases: false,
    show_in_trending: true,
    is_premium_only: false,
  },
  {
    id: 'mock-4',
    title: 'Ocean Waves',
    artist: 'Calm Shores',
    album: 'Serenity',
    cover_url: 'https://picsum.photos/seed/song4/300/300',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    duration: 312,
    genre: 'Lo-Fi',
    play_count: 6780,
    download_count: 430,
    file_size: 6100000,
    cover_size: 140000,
    is_visible: true,
    show_in_new_releases: true,
    show_in_trending: false,
    is_premium_only: false,
  },
  {
    id: 'mock-5',
    title: 'City Lights',
    artist: 'Urban Beat',
    album: 'Metropolis',
    cover_url: 'https://picsum.photos/seed/song5/300/300',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    duration: 245,
    genre: 'Hip-Hop',
    play_count: 21300,
    download_count: 1800,
    file_size: 4800000,
    cover_size: 160000,
    is_visible: true,
    show_in_new_releases: false,
    show_in_trending: true,
    is_premium_only: false,
  },
  {
    id: 'mock-6',
    title: 'Starfall',
    artist: 'Cosmic Drift',
    album: 'Galaxy',
    cover_url: 'https://picsum.photos/seed/song6/300/300',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    duration: 289,
    genre: 'Ambient',
    play_count: 4500,
    download_count: 320,
    file_size: 5600000,
    cover_size: 130000,
    is_visible: true,
    show_in_new_releases: true,
    show_in_trending: false,
    is_premium_only: false,
  },
  {
    id: 'mock-7',
    title: 'Fire Dance',
    artist: 'Blaze',
    album: 'Inferno',
    cover_url: 'https://picsum.photos/seed/song7/300/300',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    duration: 210,
    genre: 'Rock',
    play_count: 9870,
    download_count: 670,
    file_size: 4100000,
    cover_size: 110000,
    is_visible: true,
    show_in_new_releases: false,
    show_in_trending: true,
    is_premium_only: false,
  },
  {
    id: 'mock-8',
    title: 'Velvet Sky',
    artist: 'Luna Wave',
    album: 'Neon Nights',
    cover_url: 'https://picsum.photos/seed/song8/300/300',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    duration: 276,
    genre: 'Electronic',
    play_count: 7340,
    download_count: 510,
    file_size: 5300000,
    cover_size: 170000,
    is_visible: true,
    show_in_new_releases: true,
    show_in_trending: false,
    is_premium_only: false,
  },
];

export const MOCK_ARTISTS = [
  { id: 'artist-1', name: 'Luna Wave', photo_url: 'https://picsum.photos/seed/artist1/200/200', genre: 'Electronic', bio: 'Electronic music producer' },
  { id: 'artist-2', name: 'The Groove', photo_url: 'https://picsum.photos/seed/artist2/200/200', genre: 'Pop', bio: 'Pop sensation' },
  { id: 'artist-3', name: 'Neon Circuit', photo_url: 'https://picsum.photos/seed/artist3/200/200', genre: 'EDM', bio: 'EDM DJ' },
  { id: 'artist-4', name: 'Urban Beat', photo_url: 'https://picsum.photos/seed/artist4/200/200', genre: 'Hip-Hop', bio: 'Hip-hop artist' },
  { id: 'artist-5', name: 'Cosmic Drift', photo_url: 'https://picsum.photos/seed/artist5/200/200', genre: 'Ambient', bio: 'Ambient music creator' },
];

export const MOCK_STATS = {
  totalSongs: MOCK_SONGS.length,
  totalUsers: 156,
  totalPlays: MOCK_SONGS.reduce((a, s) => a + s.play_count, 0),
  totalAlbums: 5,
  totalDownloads: MOCK_SONGS.reduce((a, s) => a + s.download_count, 0),
  storageUsed: MOCK_SONGS.reduce((a, s) => a + s.file_size + s.cover_size, 0),
};

export const MOCK_PLAY_DATA = [
  { date: 'Mon', plays: 45 },
  { date: 'Tue', plays: 62 },
  { date: 'Wed', plays: 38 },
  { date: 'Thu', plays: 71 },
  { date: 'Fri', plays: 89 },
  { date: 'Sat', plays: 95 },
  { date: 'Sun', plays: 67 },
];

export const MOCK_GENRE_DATA = [
  { name: 'Electronic', value: 3 },
  { name: 'Pop', value: 1 },
  { name: 'EDM', value: 1 },
  { name: 'Hip-Hop', value: 1 },
  { name: 'Lo-Fi', value: 1 },
  { name: 'Rock', value: 1 },
];
